/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2taVoJP8htr
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import Link from "next/link";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function Login() {
  return (
    <>
      <main
        className="flex items-center justify-center h-screen"
        style={{
          backgroundImage: "url('/img/background/HMS.jpg')",
          backgroundSize: "cover",
          backgroundPosition: "center",
          backgroundRepeat: "no-repeat",
          width: "100%",
          height: "100vh",
        }}
      >
        <div className="relative w-full h-full opacity-30 bg-gray-900" />
        <Card className="max-w-md w-full space-y-8 shadow absolute">
          <CardHeader>
            <CardTitle className="mt-6 text-center text-3xl font-extrabold">
              Sign in to your account
            </CardTitle>
            <CardDescription className="mt-2 text-center text-sm text-gray-400">
              Or
              <br />
              <Link
                className="font-medium text-indigo-600 hover:text-indigo-500"
                href="/sign-up"
              >
                start your 14-day free trial
              </Link>
            </CardDescription>
          </CardHeader>
          <CardContent className="mt-8 space-y-6">
            <div>
              <div className="space-y-2">
                <Label htmlFor="phone">Phone Number</Label>
                <Input
                  autoComplete="tel"
                  className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                  id="phone"
                  placeholder="Phone number"
                  required
                  type="tel"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="password">Password</Label>
                <Input
                  autoComplete="current-password"
                  className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                  id="password"
                  placeholder="Password"
                  required
                  type="password"
                />
              </div>
            </div>
            <div className="flex items-center justify-between">
              <div className="flex items-center">
                <Input
                  className="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
                  id="remember_me"
                  name="remember_me"
                  type="checkbox"
                />
                <Label
                  className="ml-2 block text-sm text-gray-400"
                  htmlFor="remember_me"
                >
                  Remember me
                </Label>
              </div>
              <div className="text-sm">
                <Link
                  className="font-medium text-indigo-600 hover:text-indigo-500"
                  href="#"
                >
                  Forgot your password?
                </Link>
              </div>
            </div>
            <div>
              <Link href="/dashboard">
                <Button
                  className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                  type="submit"
                >
                  Sign in
                </Button>
              </Link>
            </div>
          </CardContent>
        </Card>
      </main>
    </>
  );
}
